### Variables
@baseUrl = http://localhost:3000

### 1. Criar Novo Restaurante + Dono Mestre
POST {{baseUrl}}/restaurantes
Content-Type: application/json

{
  "nome": "Pizzaria do Pedro",
  "cnpj": "12.345.678/0001-99",
  "email": "contato@pizzariadopedro.com",
  "nomeDono": "Pedro Silva",
  "cpf": "12345678900",
  "senha": "SenhaSegura123"
}

###

### 2. Listar Todos os Restaurantes (Para pegar o código gerado)
GET {{baseUrl}}/restaurantes

###

### 3. Adicionar um Funcionário Comum
# ATENÇÃO: Substitua o REST-1001 abaixo pelo código que o seu GET retornou!
POST {{baseUrl}}/restaurantes/REST-1001/funcionarios
Content-Type: application/json

{
  "nome": "João Garçom",
  "cpf": "98765432100",
  "senha": "SenhaDoJoao123",
  "permissoes": {
    "canCheckStocks": true,
    "canSeeFinancialReports": false,
    "canDoOrders": true,
    "canSeeOrders": true,
    "canChangeOrderState": true,
    "canCancelOrder": false
  }
}